#!/bin/bash
set -e

bail() {
    local reset_colour='\e[0m'
    local red="${COLOUR_ERROR:-\e[38;5;196m}"
    echo -e "${red}$1${reset_colour}"
    exit 1
}

gitBehindRemote() {
    git remote update >/dev/null
    local oldrev=$(git rev-parse HEAD)
    if [[ $oldrev != $(git rev-parse @{u}) ]]; then
        return 0
    else
        return 1
    fi
}

top=$(git rev-parse --show-toplevel)
if [ ! -e $top/.overcommit.yml ]; then
    bail "Missing .overcommit.yml. Run:\ncurl -s https://raw.githubusercontent.com/dstil/git-hooks/master/.overcommit.yml > $top/.overcommit.yml"
fi

# Have to use perl because OSX grep is useless
if ! perl -n000e 'exit ! (/^(\s+)OvercommitConfig:\n\1\s+enabled: true$/m)' "$top/.overcommit.yml"; then
    bail ".overcommit.yml must contain the following:\nPreCommit:\n  OvercommitConfig:\n    enabled: true"
fi

if [ ! -e $top/.git-hooks/.git ]; then
    bail ".git-hooks is not a Git repository or submodule. Run:\nGIT_TEMPLATE_DIR='' git submodule add https://github.com/dstil/git-hooks $top/.git-hooks"
fi

pushd $top/.git-hooks >/dev/null
    if gitBehindRemote; then
        bail ".git-hooks is not up to date. Run:\ngit submodule foreach git pull"
    fi
popd >/dev/null
