#!/bin/bash
set -e

bail() {
    local reset_colour='\e[0m'
    local red="${COLOUR_ERROR:-\e[38;5;196m}"
    echo -e "${red}$1${reset_colour}"
    exit 1
}

top=$(git rev-parse --show-toplevel)
if [ ! -e $top/.overcommit.yml ]; then
    bail "Missing .overcommit.yml"
fi

if ! grep -Pzq "^(\s+)OvercommitConfig:\n\1\s+enabled: true" "$top/.overcommit.yml"; then
    bail ".overcommit.yml must contain the following:\nPreCommit:\n  OvercommitConfig:\n    enabled: true"
fi
