#!/usr/bin/env python

import filecmp
import functools
import os
import os.path
import subprocess
import sys
import urllib
import ruamel.yaml as yaml

NAME='dstil'

def git_toplevel():
    try:
        return subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).strip()
    except subprocess.CalledProcessError, e:
        if e.returncode == 128: # Probably not a git repo
            return None
        else:
            raise

def print_colour(colour, msg):
    print('\033[{}{}\033[0m'.format(colour, msg))

errol = functools.partial(print_colour, os.environ.get('COLOUR_ERROR', '38;5;196m'))
warn = functools.partial(print_colour, '93m')

def cmd_emphasis(msg):
    return '\033[1m{}\033[21m'.format(msg)

def warn_sign(will_sign):
    if not will_sign:
        warn('Overcommit hooks changed. You may want to run ' + cmd_emphasis(NAME + ' --sign') + '.')

def deepset(d, key, value):
    dd = d
    keys = key.split('.')
    latest = keys.pop()
    for k in keys:
        dd = dd.setdefault(k, {})
    dd[latest] = value

def check_overcommit(fix=False, will_sign=False):
    fn = '.overcommit.yml'
    exists = os.path.exists(fn)

    if exists:
        if not os.path.isfile(fn):
            return ".overcommit.yml exists and is not a file"
        else:
            with open(fn, 'r+') as f:
                y = yaml.load(f, yaml.RoundTripLoader)
                try:
                    if y['PreCommit']['OvercommitConfig']['enabled'] != True:
                        raise KeyError()
                except KeyError:
                    if fix:
                        deepset(y, 'PreCommit.OvercommitConfig.enabled', True)
                        f.seek(0)
                        f.truncate()
                        f.write(yaml.dump(y, Dumper=yaml.RoundTripDumper))
                        subprocess.check_call(['git', 'add', '.overcommit.yml'])
                        warn_sign(will_sign)
                    else:
                        return '.overcommit.yml must contain:\nPreCommit:\n  OvercommitConfig:\n    enabled: true'

    else:
        if fix:
            urllib.urlretrieve('https://raw.githubusercontent.com/dstil/git-hooks/master/.overcommit.yml', fn)
            subprocess.check_call(['git', 'add', '.overcommit.yml'])
            warn_sign(will_sign)
        else:
            return ".overcommit.yml does not exist"

def check_git_hooks_behind(hooks_dir, fix=False, will_sign=False):
    d = os.getcwd()
    try:
        os.chdir(hooks_dir)
        # Suppress output
        subprocess.check_output(['git', 'remote', 'update'])
        cur_head = subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip()
        remote_head = subprocess.check_output(['git', 'rev-parse', '@{u}']).strip()
        if cur_head != remote_head:
            if fix:
                subprocess.check_call(['git', 'pull'])
            else:
                return '.git-hooks is not up to date'
    finally:
        os.chdir(d)

def check_git_hooks(fix=False, will_sign=False):
    hooks_dir = '.git-hooks'
    if os.path.isdir(hooks_dir):
        return check_git_hooks_behind(hooks_dir, fix=fix)
    elif fix:
        nenv = os.environ.copy()
        nenv['GIT_TEMPLATE_DIR'] = ''
        subprocess.check_call(['git', 'submodule', 'add', 'https://github.com/dstil/git-hooks', hooks_dir], env=nenv)
    else:
        return '.git-hooks does not exist'

def check_overcommit_hooks(fix=False, will_sign=False):
    try:
        overcommit_template = subprocess.check_output(['overcommit', '--template-dir']).strip()
    except OSError, e:
        if e.errno == 2:
            if fix:
                return 'No, you:\n  gem install overcommit'
            else:
                return 'Overcommit is not installed'
        else:
            raise
    cmpd = filecmp.dircmp(overcommit_template + '/hooks', '.git/hooks')
    if (cmpd.left_only or cmpd.diff_files):
        if fix:
            subprocess.check_call(['overcommit', '--install'])
            warn_sign(will_sign)
        else:
            return 'Overcommit hooks not initialised in this repository'

def run_checks(checks, fix=False, will_sign=False):
    for check in checks:
        msg = check(fix=fix, will_sign=will_sign)
        if msg:
            errol(msg)
            return False
    return True

def overcommit_sign():
    subprocess.check_call(['overcommit', '--sign'])
    for hk in ['pre-commit', 'commit-msg', 'pre-push']:
        subprocess.check_call(['overcommit', '--sign', hk])

def main():
    toplevel = git_toplevel()
    if not toplevel:
        # Git already provides an error message
        return

    os.chdir(toplevel)
    fix = '--fix' in sys.argv[1:]
    sign = '--sign' in sys.argv[1:]
    if not run_checks([check_overcommit, check_overcommit_hooks, check_git_hooks], fix=fix, will_sign=sign) and not fix:
        print('Try to fix with ' + cmd_emphasis(NAME + ' --fix'))
    if sign:
        overcommit_sign()

if __name__ == '__main__':
    main()
